language: ruby
rvm:
  - 2.1.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script: "bundle exec rspec spec/"
deploy:
  provider: heroku
  api_key: "f4daee49-05d3-498f-946a-314aa8d94c52"