development:
  compass_root_url: https://compass.lsus.edu
  compass_home: https://compass.lsus.edu/FCCSC/registration/coursesearch.jsp
test:
  compass_root_url: https://compass.lsus.edu
  compass_home: https://compass.lsus.edu/FCCSC/registration/coursesearch.jsp
production:
  compass_root_url: https://compass.lsus.edu
  compass_home: https://compass.lsus.edu/FCCSC/registration/coursesearch.jsp